name: "sac"

gamma: 0.99
automatic_entropy_tuning: true
target_entropy: "auto" 
tau: 0.005
lr_actor: 1e-3
lr_critic: 1e-3
lr_alpha: 3e-4  
hidden_dims: [256, 256, 256]

lambda_actor: 1.0
lambda_critic: 10.0
